services:
  client:
    container_name: "gdd"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: deps
    ports:
      - "${PORT}:${PORT}"
    expose:
      - ${PORT}
    networks:
      - gdd
    restart: always

networks:
  gdd:
    external: true